apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tkngate.fullname" . }}
  labels:
    {{- include "tkngate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tkngate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tkngate.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "tkngate.fullname" .) }}
      {{- end }}
      containers:
        - name: tkngate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
            - name: telemetry
              containerPort: {{ .Values.config.telemetry.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/tkngate.yaml
              subPath: tkngate.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: telemetry
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: telemetry
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ include "tkngate.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
