apiVersion: v1
kind: Service
metadata:
  name: {{ include "tkngate.fullname" . }}
  labels:
    {{- include "tkngate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
    - name: telemetry
      port: {{ .Values.service.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "tkngate.selectorLabels" . | nindent 4 }}
